/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lottery;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Carl
 */
public class LotteryGUI extends javax.swing.JFrame {

    private ArrayList<Lottery> userList;
    //private String gameType;
    private int userNum1, userNum2, userNum3, userNum4, userNum5, count;

    /**
     * Creates new form LotteryGUI
     */
    public LotteryGUI() {
        initComponents();
        userList = new ArrayList<>();
        //gameType = new String();
        userNum1 = 0;
        userNum2 = 0;
        userNum3 = 0;
        userNum4 = 0;
        userNum5 = 0;
        count = 0;

        //instructions1JL.setVisible(false);
        //instructions2JL.setVisible(false);
        //userNum1Tf.setVisible(false);
        //userNum2Tf.setVisible(false);
        //userNum3Tf.setVisible(false);
        //userNum4Tf.setVisible(false);
        //userNum5Tf.setVisible(false);
        //play1Btn.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgrnd = new javax.swing.JPanel();
        lottoPlusJB = new java.awt.Button();
        lottoJB = new java.awt.Button();
        instructions1JL = new java.awt.Label();
        instructions2JL = new java.awt.Label();
        userNum1Tf = new javax.swing.JTextField();
        userNum2Tf = new javax.swing.JTextField();
        userNum3Tf = new javax.swing.JTextField();
        userNum4Tf = new javax.swing.JTextField();
        userNum5Tf = new javax.swing.JTextField();
        play1Btn = new java.awt.Button();
        ballsPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 480));
        setResizable(false);

        backgrnd.setLayout(null);

        lottoPlusJB.setBackground(new java.awt.Color(0, 0, 204));
        lottoPlusJB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lottoPlusJB.setForeground(new java.awt.Color(255, 255, 204));
        lottoPlusJB.setLabel("Click to play LOTTO PLUS");
        lottoPlusJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoPlusJBActionPerformed(evt);
            }
        });
        backgrnd.add(lottoPlusJB);
        lottoPlusJB.setBounds(270, 150, 290, 30);

        lottoJB.setBackground(new java.awt.Color(0, 0, 204));
        lottoJB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lottoJB.setForeground(new java.awt.Color(255, 255, 204));
        lottoJB.setLabel("Click to play LOTTO");
        lottoJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoJBActionPerformed(evt);
            }
        });
        backgrnd.add(lottoJB);
        lottoJB.setBounds(270, 110, 290, 30);

        instructions1JL.setAlignment(java.awt.Label.CENTER);
        instructions1JL.setBackground(new java.awt.Color(255, 255, 204));
        instructions1JL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        instructions1JL.setText("YOU HAVE 3 LINES TO PLAY!");
        backgrnd.add(instructions1JL);
        instructions1JL.setBounds(120, 20, 580, 40);

        instructions2JL.setBackground(new java.awt.Color(255, 255, 204));
        instructions2JL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        instructions2JL.setText("PLEASE ENTER 5 NUMBERS BETWEEN 1 AND 40");
        backgrnd.add(instructions2JL);
        instructions2JL.setBounds(120, 60, 580, 40);

        userNum1Tf.setBackground(new java.awt.Color(255, 255, 204));
        backgrnd.add(userNum1Tf);
        userNum1Tf.setBounds(230, 200, 50, 50);

        userNum2Tf.setBackground(new java.awt.Color(255, 255, 204));
        backgrnd.add(userNum2Tf);
        userNum2Tf.setBounds(310, 200, 50, 50);

        userNum3Tf.setBackground(new java.awt.Color(255, 255, 204));
        backgrnd.add(userNum3Tf);
        userNum3Tf.setBounds(390, 200, 50, 50);

        userNum4Tf.setBackground(new java.awt.Color(255, 255, 204));
        backgrnd.add(userNum4Tf);
        userNum4Tf.setBounds(470, 200, 50, 50);

        userNum5Tf.setBackground(new java.awt.Color(255, 255, 204));
        backgrnd.add(userNum5Tf);
        userNum5Tf.setBounds(550, 200, 50, 50);

        play1Btn.setBackground(new java.awt.Color(0, 0, 204));
        play1Btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        play1Btn.setForeground(new java.awt.Color(255, 255, 204));
        play1Btn.setLabel("Click to play this line");
        play1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play1BtnActionPerformed(evt);
            }
        });
        backgrnd.add(play1Btn);
        play1Btn.setBounds(270, 280, 290, 30);

        ballsPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carl\\Downloads\\AAA My Folders\\College\\2016\\Object Orientated Programming\\Project LOTTO\\001 GUI\\Images\\01Balls.jpg")); // NOI18N
        backgrnd.add(ballsPic);
        ballsPic.setBounds(0, 0, 800, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lottoJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoJBActionPerformed

    private void lottoPlusJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoPlusJBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lottoPlusJBActionPerformed

    private void play1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play1BtnActionPerformed
        while (count < 3) {
            //get the text from text the fields
            //gameType = gameTypeTF.getText();
            userNum1 = Integer.parseInt(userNum1Tf.getText());
            userNum2 = Integer.parseInt(userNum2Tf.getText());
            userNum3 = Integer.parseInt(userNum3Tf.getText());
            userNum4 = Integer.parseInt(userNum4Tf.getText());
            userNum5 = Integer.parseInt(userNum5Tf.getText());

            Lottery a = new Lottery();
            //a.setGameType(gameType);
            a.setUserNum1(userNum1);
            a.setUserNum2(userNum2);
            a.setUserNum3(userNum3);
            a.setUserNum4(userNum4);
            a.setUserNum5(userNum5);

            //add object to array list
            /*userList.add(a);
        userNum1Tf.setText("");
        userNum2Tf.setText("");
        userNum3Tf.setText("");
        userNum4Tf.setText("");
        userNum5Tf.setText("");
        //gameTypeTF.setText("");
             */
            //increase the counter
            count++;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_play1BtnActionPerformed
 public ArrayList<Lottery> getUserList() {
        return userList;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotteryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotteryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotteryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotteryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LotteryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgrnd;
    private javax.swing.JLabel ballsPic;
    private java.awt.Label instructions1JL;
    private java.awt.Label instructions2JL;
    private java.awt.Button lottoJB;
    private java.awt.Button lottoPlusJB;
    private java.awt.Button play1Btn;
    private javax.swing.JTextField userNum1Tf;
    private javax.swing.JTextField userNum2Tf;
    private javax.swing.JTextField userNum3Tf;
    private javax.swing.JTextField userNum4Tf;
    private javax.swing.JTextField userNum5Tf;
    // End of variables declaration//GEN-END:variables
}
