/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotto;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carl
 */
public class LottoPlusGUI extends javax.swing.JFrame {

    private ArrayList<Line> objectLines;
    private String gameType;
    private int userNums1, userNums2, userNums3, userNums4, userNums5;
    private String total;
    private int lottoNums [];
    private int lottoPlusOneNums [];
    private int lottoPlusTwoNums [];

    /**
     * Creates new form LottoGUI
     */
    public LottoPlusGUI() {
        initComponents();
        objectLines = new ArrayList<>();
        gameType = new String();
        userNums1 = 0;
        userNums2 = 0;
        userNums3 = 0;
        userNums4 = 0;
        userNums5 = 0;
        lottoNums = new int[5];
        lottoPlusOneNums = new int[5];
        lottoPlusTwoNums = new int[5];
        

    }

    
    
    

    Lotto myLotto = new Lotto(lottoNums, lottoPlusOneNums, lottoPlusTwoNums, objectLines);
    LottoNums myNumbers = new LottoNums();
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        gameText1Lbl = new javax.swing.JLabel();
        gameText2Lbl = new javax.swing.JLabel();
        userNum1Tf = new javax.swing.JTextField();
        userNum2Tf = new javax.swing.JTextField();
        userNum3Tf = new javax.swing.JTextField();
        userNum4Tf = new javax.swing.JTextField();
        userNum5Tf = new javax.swing.JTextField();
        gameTypeTF = new javax.swing.JTextField();
        playBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 255, 102));
        setForeground(java.awt.Color.magenta);
        setIconImages(null);

        titleLbl.setBackground(new java.awt.Color(255, 255, 204));
        titleLbl.setFont(new java.awt.Font("Valken", 1, 48)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(204, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Lottery Game");

        gameText1Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gameText1Lbl.setText("Please enter 5 numbers between 1 and 40");

        gameText2Lbl.setBackground(new java.awt.Color(255, 255, 204));
        gameText2Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gameText2Lbl.setText("Which game would you like to play for this line? Enter lotto, plus1, or plus2");

        userNum1Tf.setBackground(new java.awt.Color(255, 255, 204));
        userNum1Tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNum1Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNum1TfActionPerformed(evt);
            }
        });

        userNum2Tf.setBackground(new java.awt.Color(255, 255, 204));
        userNum2Tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNum2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNum2TfActionPerformed(evt);
            }
        });

        userNum3Tf.setBackground(new java.awt.Color(255, 255, 204));
        userNum3Tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNum3Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNum3TfActionPerformed(evt);
            }
        });

        userNum4Tf.setBackground(new java.awt.Color(255, 255, 204));
        userNum4Tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNum4Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNum4TfActionPerformed(evt);
            }
        });

        userNum5Tf.setBackground(new java.awt.Color(255, 255, 204));
        userNum5Tf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNum5Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNum5TfActionPerformed(evt);
            }
        });

        gameTypeTF.setBackground(new java.awt.Color(255, 255, 204));
        gameTypeTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gameTypeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gameTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameTypeTFActionPerformed(evt);
            }
        });

        playBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playBtn.setForeground(new java.awt.Color(0, 0, 204));
        playBtn.setText("Click to play this line");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Display Numbers guessed");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameText2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(playBtn)
                                        .addGap(66, 66, 66)
                                        .addComponent(jButton3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(gameTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(titleLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(gameText1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(userNum1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(userNum2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(userNum3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(userNum4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(userNum5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(560, 560, 560))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameText1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userNum1Tf)
                    .addComponent(userNum2Tf)
                    .addComponent(userNum3Tf)
                    .addComponent(userNum4Tf)
                    .addComponent(userNum5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(gameText2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playBtn)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("Display numbers");
        jButton1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNum2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNum2TfActionPerformed

    }//GEN-LAST:event_userNum2TfActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
        //for(int i = 0;i<3;i++){

        for (int i = 0; i < 3; i++) {
            //get the text from text the fields
            Line eachLine = new Line();
            gameType = gameTypeTF.getText();
            userNums1 = Integer.parseInt(userNum1Tf.getText());
            userNums2 = Integer.parseInt(userNum2Tf.getText());
            userNums3 = Integer.parseInt(userNum3Tf.getText());
            userNums4 = Integer.parseInt(userNum4Tf.getText());
            userNums5 = Integer.parseInt(userNum5Tf.getText());

            userNum1Tf.setText("");
            userNum2Tf.setText("");
            userNum3Tf.setText("");
            userNum4Tf.setText("");
            userNum5Tf.setText("");
            gameTypeTF.setText("");

            eachLine.setGameType(gameType);//V.V setting users value to gameType
            //gameType = "";
            eachLine.setUserNums1(userNums1);//V.V setting users value to userNums1
            eachLine.setUserNums2(userNums2);//V.V setting users value to userNums2
            eachLine.setUserNums3(userNums3);//V.V setting users value to userNums3
            eachLine.setUserNums4(userNums4);//V.V setting users value to userNums4
            eachLine.setUserNums5(userNums5);//V.V setting users value to userNums5

            objectLines.add(eachLine);//V.V Adding eachLine object to ArrayList called objectLines
    }//GEN-LAST:event_playBtnActionPerformed
    
    }
    
  
    
    private void userNum1TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNum1TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNum1TfActionPerformed

    private void gameTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameTypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameTypeTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (int j = 0; j < objectLines.size(); j++) {
            JOptionPane.showMessageDialog(null, "You are playing " + objectLines.get(j).getGameType() + " .\nThe numbers you chose are: " + objectLines.get(j).getUserNums1() + ", " + objectLines.get(j).getUserNums2() + ", " + objectLines.get(j).getUserNums3() + ", " + objectLines.get(j).getUserNums4() + ", " + objectLines.get(j).getUserNums5() + ".");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userNum3TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNum3TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNum3TfActionPerformed

    private void userNum4TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNum4TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNum4TfActionPerformed

    private void userNum5TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNum5TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNum5TfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        myNumbers.lottoNums();
        

        //V.V Getting genereated number from LottoNums class
        lottoNums = myNumbers.getLottoNums();
        System.out.println(Arrays.toString(lottoNums));
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoPlusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoPlusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoPlusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoPlusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LottoPlusGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameText1Lbl;
    private javax.swing.JLabel gameText2Lbl;
    private javax.swing.JTextField gameTypeTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton playBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField userNum1Tf;
    private javax.swing.JTextField userNum2Tf;
    private javax.swing.JTextField userNum3Tf;
    private javax.swing.JTextField userNum4Tf;
    private javax.swing.JTextField userNum5Tf;
    // End of variables declaration//GEN-END:variables
}
